##############################################################
# Build that shit.
##############################################################
build:
    stage: build
    image: node:10
    only:
        - master
        - develop
    except:
        - tags
    script:
        - yarn install
        - yarn build
    artifacts:
        paths:
            - ./bin

##############################################################
# Deployment.
##############################################################
deploy/npm:
    stage: deploy
    image: node:10
    only:
        - master
    except:
        - tags
    script:
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        - npm publish
